export enum BookCategory {
  ALL = "All",
  FICTION = "Fiction",
  ADVENTURE = "Adventure",
  CLASSIC_NOVELS = "Classic Novels",
  MYSTERY_CRIME_THRILLER = "Mystery, Crime & Thriller",
  ROMANCE = "Romance",
  HORROR = "Horror",
  FANTASY = "Fantasy",
  SCIENCE_FICTION = "Science Fiction",
  HISTORICAL_FICTION = "Historical Fiction",
  PHILOSOPHY = "Philosophy",
  HISTORY = "History",
  SPORTS = "Sports",
  FOOD_BEVERAGE = "Food & Beverage",
  WILDLIFE_NATURE = "Wildlife & Nature",
  GARDENING = "Gardening",
  SCIENCE = "Science",
  COMICS_MANGA = "Comics & Manga",
  MANGA = "Manga",
}
